# @author : https://github.com/Fanqie22
# @date : 2018年12月19日10:55:08
# @description : 编码格式 : please use UTF-8 你完全不用告诉Spring Boot 这里有一个配置文件 ,它会自动找到这个自动生成的文件并加载它
# 修改Tomcat监听端口,默认是8080
# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
    min-spare-threads: 10
  port: 8080
  connection-timeout: 5000ms
  servlet:
    context-path: /


spring:
  devtools:
    restart:
      additional-exclude: templates/**
      enabled: true
  #Thymeleaf渲染模板设置
  thymeleaf:
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML5
    cache: false
  #durid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
    url: jdbc:mysql://127.0.0.1:3306/microclouds?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: microcloudsdatabase
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 6000
  # session ，用redis缓存 TODO
  session:
    store-type: none
  # mail
  mail:
    host:
    username:
    password:
    default-encoding: UTF-8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000ms
    jedis:
      pool:
        max-active: 50
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 20480MB


#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.microclouds.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
#    #逻辑删除配置（下面3个配置）
#    logic-delete-value: 1
#    logic-not-delete-value: 0
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
#    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'